In this notebook we will look into matrix factorization.

Matrix factorization is used to represent a given large matrix into a product of two or more, smaller matrices. 
One important use is to save memory.

Let A be a square matrix, our goal is to find two matrices whose multiplication will result in A.

Matrix factorization is also known as matrix decomposition.

Different matrix facorizations such as:

1) LU decomposition

2) QR decomposition

3) Cholesky decomposition

4) Singular Value Decomposition (SVD)

In [2]:
import numpy as np
from scipy import linalg

Let us first look at a system of equations:
    
$ x_1 + x_2 = 7 $

$ 2x_1 - x_2 = 8 $

Our goal is to find $x_1$ and $x_2$ using elimination. 

Now let's solve the above equations by converting them into matrices.

Let's define det(A) 

Determinant of a matrix A is a scalar that is further used to solve a system of linear equations.

Let's consider an example

Reference: https://math.oregonstate.edu/home/programs/undergrad/CalculusQuestStudyGuides/vcalc/deter/deter.html
        
<img src="images/determinant.png" width=500, height=400>

In [2]:
a = np.array([[2, -3], [1, 12]])
print(linalg.det(a))

27.0


Let us look at an example for inverse of a matrix

Reference: https://www.mathsisfun.com/algebra/matrix-inverse.html

<img src="images/inverse_matrix.png" width=500, height=300>

Now let us now solve the system of equations that we considered initially 

$ x_1 + x_2 = 7 $

$ 2x_1 - x_2 = 8 $

Let us find $x_1$ and $x_2$ by computing the matrix inverse. 
We will solve this on the board. 

In [3]:
A = np.array([[1, 1], [2, -1]])
B = np.array([7, 8])
Ainverse = linalg.inv(A)
print(Ainverse)
Sol = Ainverse.dot(B)
print(Sol)

[[ 0.33333333  0.33333333]
 [ 0.66666667 -0.33333333]]
[5. 2.]


In [4]:
"""
In-class activity: Can you solve the system of equations 

2x_1 + x_2 = 9

3x_1 - x_2 = 11

1) Using Gaussian Elimination

2) Finding inverse

3) Using Scipy.
"""

# part 3

A = np.array([[2, 1], [3, -1]])
B = np.array([9, 11])

Ainv = linalg.inv(A)
solution = Ainv.dot(B)
print(solution)

[4. 1.]


#### Eigen Values and Eigen Vectors

Eigen values help us explain characteristics of a matrix. In the following equation, $\lambda$ is known as the eigen value and $v$ is known as the eigen vector. 

$ A v = \lambda v $

#### Example on computing eigen value and eigen vector

Reference: https://lpsa.swarthmore.edu/MtrxVibe/EigMat/MatrixEigen.html


<img src="images/eigen_example2.png">

In [5]:
A = np.array([[0, 1], [-2, -3]])
value, v = linalg.eig(A)
print(value)
print(v)

[-1.+0.j -2.+0.j]
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [6]:
"""
In-class activity: Find the eigen values and eigen vectors for the following 

A = [[-2, 1], [5, 2]]

1) Find them by solving mathematically

2) Use Scipy
"""
A = np.array([[-2, 1], [5, 2]])
value, v = linalg.eig(A)
print(value)
print(v)

[-3.+0.j  3.+0.j]
[[-0.70710678 -0.19611614]
 [ 0.70710678 -0.98058068]]


#### LU Decomposition

LU Decomposition
$A = L * U = LU $

A is a square matrix, L and U are triangular matrices.
<img src=images/LU.png>

#### LU decomposition using Dolittle computation

References: https://www.quantstart.com/articles/LU-Decomposition-in-Python-and-NumPy

http://mathonline.wikidot.com/doolittle-s-method-for-lu-decompositions
        
<img src=images/dolittle_computational.png>

In [7]:
alu = np.array([[2, 3, 2], [1, 3, 2], [3, 4, 1]])
P, L, U = linalg.lu(alu)
print(P) # Pivot Matrix
print("+++++++++")
print(L)
print("+++++++++")
print(U)
print(np.allclose(alu - P@ L @ U, np.zeros((3, 3))))

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
+++++++++
[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.66666667 0.2        1.        ]]
+++++++++
[[3.         4.         1.        ]
 [0.         1.66666667 1.66666667]
 [0.         0.         1.        ]]
True


#### SVD 

$A = U \Sigma V^T $

where U and V are orthonormal i.e. their columns are orthogonal and unit vectors.

U and V are unitary matrices that means $U U^T = I$ and $V V^T = I$

https://medium.com/@jonathan_hui/machine-learning-singular-value-decomposition-svd-principal-component-analysis-pca-1d45e885e491

        
<img src=images/svd.png>

In [8]:
a = np.array([[3, 4],[ 9, 8]])
U, s, Vh = linalg.svd(a)
print(U.shape,  s.shape, Vh.shape)
print(U)
print("++++++")
print(s)
print("++++++")
print(Vh)

(2, 2) (2,) (2, 2)
[[-0.37879831 -0.92547925]
 [-0.92547925  0.37879831]]
++++++
[13.00571713  0.92267115]
++++++
[[-0.72781132 -0.68577743]
 [ 0.68577743 -0.72781132]]
