## Numpy

Travis Oliphant created Numpy and released it to public as Numeric in 1995 and as Numpy in 2006. 
It is written in Python and C. Now it is maintained by Python Community. 

Numpy is a powerful library that is used for numerical computing. Libraries such as Pandas and Tensorflow are build on Numpy. In Tensorflow, the output is an ndarray, which stands for n-dimensional array. 

## Arrays vs Matrices 

https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html

In Numpy, matrices are two dimensional whereas arrays can be of any dimension, i.e. n-dimensional.

In [1]:
import numpy as np

# here np is an alias for numpy

In [2]:
# simple way of creating an empty numpy array
# array is a numpy function, so it is always going to have (), 
# since functions have input arguments, that's why we have ()
# inside the [], we can give values 

a = np.array([])

## NDARRAY
An ndaray is a n-dimensional array where all items are of the same type (unlike a Python data structure) and consequently use the same amount of space. There are 21 different types of objects (also called dtypes) that can be stored in ndarray, such as
* bool_ 
* byte
* short
* int_
* single
* float_
* longfloat
* complex_
* object_
* str_

For some of the dtypes, a _ to differentiate that dtype from the corresponding Python type. Such types are also called as 'enhanced scalars).  They have the same precision as the Python type.


Creating Arrays - First let's learn about different ways of create arrays in numpy. 

In [3]:
# declaring a simple one dimensional numpy array

a = [2, 6, 10] # here a is a list that contains three values
print(a, type(a), type(a[2]))

a = np.array(a) # we are converting a into a numpy array
print(a, type(a), a.dtype)

[2, 6, 10] <class 'list'> <class 'int'>
[ 2  6 10] <class 'numpy.ndarray'> int32


In [4]:
# declaring another simple one dimensional numpy array

a = np.array([1, 2, 3, 4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# declaring a two dimensional numpy array

b = np.array([[1, 2, 3], [4, 5, 6]])
# note that we have to supply each row of the array as an item in a list
print(b)
print(b.shape) # shape will return the shape of the array, in this case we have two rows and three columns
print(b.ndim) # ndim will return the dimension of the nd array

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [6]:
# declaring a numpy matrix, strictly two dimensional

b = np.matrix([[1, 2, 3], [4, 5, 6]])
# note that we have to supply each row of the array as an item in a list
print(b, type(b))
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]] <class 'numpy.matrix'>
(2, 3)
2


In [7]:
# we can create a simple ndarray by using arange
# numpy.arange(n) will create an ndarray elements starting from 0 to n-1

a = np.arange(7) # will create elements starting from 0 to 7-1
print(a)
print(type(a))

[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
# we can also include negative integers

a1 = np.arange(-7, 7)
print(a1)

[-7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6]


In [9]:
# can have step size 
a2 = np.arange(start=-10, stop=10, step=2)
print(a2)

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [22]:
# Create 10 numbers between 1 and 20 including 20
p = np.linspace(start = 1, stop = 20, num=10)
print('The linear space of value is {0}'.format(p))

The linear space of value is [ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [11]:
"""
In-class activity - create an array using linspace that starts from -5 and stops at 5 and num = 10
"""
p = np.linspace(-5, 5, 10)
print(p)

[-5.         -3.88888889 -2.77777778 -1.66666667 -0.55555556  0.55555556
  1.66666667  2.77777778  3.88888889  5.        ]


In [12]:
"""
In logspace the values are computed by taking 10 power the value
note that 10 power 0.1 is 1.25892541
"""

p = np.logspace(start = 0.1, stop = 0.20, num=10)
print('The log space of value is {0}'.format(p))
print(type(p))

The log space of value is [1.25892541 1.29154967 1.32501936 1.35935639 1.39458325 1.43072299
 1.46779927 1.50583635 1.54485915 1.58489319]
<class 'numpy.ndarray'>


In [13]:
import math
math.pow(10, 0.10)

1.2589254117941673

In [14]:
"""
In-class activity - Create an array with logspace that starts from -4 and stops at 4 and num = 6.
"""
p = np.logspace(start = -4, stop = 4, num=6)
print('The log space of value is {0}'.format(p))
print(type(p))

The log space of value is [1.00000000e-04 3.98107171e-03 1.58489319e-01 6.30957344e+00
 2.51188643e+02 1.00000000e+04]
<class 'numpy.ndarray'>


In [15]:
# using zeros() method
a = np.zeros((3, 2))
print(a)

# np.zeros is used for initialization

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
# using ones() method
a = np.ones((3,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
# using identity
a = np.identity(4) 
print(a)

# identity is always going to return a square nd array with a diagonal of 1s

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
import numpy as np
# using empty() method 
# this will generate very small random numbers close to zero
b = np.empty((3,3), dtype=np.int32) 
print(b) 

[[      1536         15      25344]
 [        30   23330816    7602813]
 [1116668035   58459005    8126880]]


In [19]:
"""
In-class activity: In the above variable b, change b[0][1] to 15 and b[1][0] to 30 and then print b. 
"""
b[0][1] = 15
b[1][0] = 30
print(b)

[[      1536         15      25344]
 [        30   23330816    7602813]
 [1116668035   58459005    8126880]]


In [20]:
np.zeros_like(b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

References:

http://people.duke.edu/~ccc14/pcfb/numpympl/NumpyBasics.html

https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

http://www.engr.ucsb.edu/~shell/che210d/numpy.pdf

http://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html

http://www.labri.fr/perso/nrougier/teaching/numpy.100/

NUMPY TO MATLAB - https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html

https://www.numpy.org/devdocs/user/numpy-for-matlab-users.html