In this notebook we will discuss the following:
    
Reshape

Resize

ravel

flatten

ufunc

broadcast

indexing

In [1]:
import numpy as np

In [2]:
# ndim will return number of ndarray dimensions
a = np.arange(12)
print(a) 
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1


In [3]:
b = np.array([[2, 5], [8, 11], [4, 17]])
print(b)
print(b.ndim)

[[ 2  5]
 [ 8 11]
 [ 4 17]]
2


In [4]:
a = np.zeros((4, 5, 6, 7, 8, 9))
a.ndim

6

In [5]:
# reshape() will reshape the array into the specified shape
a = np.arange(8) # we are creating an array with value 0, 1,..., 7
b = a.reshape((2, 4)) # Create a new array to size 2x4 
print(a)
print(b) 

# this works because 2*4 = 8 

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [30]:
a1 = np.arange(10)
b1 = a1.reshape((2, 5)) # Create a new array to size 2x4 
print(a1)
print(b1) 

# this failed because 2*4 is not equal to 10

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [7]:
c = a.resize((4,2)) # Update memory at 'a' to become an array , c is empty, saves memory
print(c) 
# the above line will return None as resize modifies inplace 
# while reshape creates a new array 
print(a)

None
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [8]:
b = np.arange(9)
b.resize((3,3))
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
flat_b = b.flatten()
print(flat_b)
# since flat_b is a new copy, any change to flat_b does not affect b

[0 1 2 3 4 5 6 7 8]


In [10]:
flat_b[0] = -100
print('flat_b:')
print(flat_b)
print('b:')
print(b)

flat_b:
[-100    1    2    3    4    5    6    7    8]
b:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
ravel_b = b.ravel()
print(ravel_b)
# ravel_b is not a copy, any change to ravel_b affects b 

[0 1 2 3 4 5 6 7 8]


In [12]:
ravel_b[0] = 10
print(ravel_b)
print(b)
# ravel_b is not a copy, any change to ravel_b affects b 

[10  1  2  3  4  5  6  7  8]
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [13]:
# for a 2 dimensional array, we have to do double indexing
# b[0][0] will represent the first value in the first row
# b[0][1] will be the second value in the first row
# b[0][2] will be the third value in the first row
# b[2][1] = 7

In [14]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [15]:
# good time to talk about shallow copy vs deep copy

# shallow copy
d = a
a[0][0] = -4
print(a)
print(d)
# note that d and a will have same values even though we modified only a

[[-4  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]
[[-4  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]


In [16]:
# Deep copy
e = a.copy()
a[0][0] = 3
print(a)
print(e)
# note that e and a will have different values

[[3 1]
 [2 3]
 [4 5]
 [6 7]]
[[-4  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]]


In [17]:
"""
In-class activity - create an ndarray using arange that starts at 0 and stops 
at 12 in increments of 3. Then reshape the array to 2,2 then ravel the array. 
At each step, print the output.
"""

'\nIn-class activity - create an ndarray using arange that starts at 0 and stops \nat 12 in increments of 3. Then reshape the array to 2,2 then ravel the array. \nAt each step, print the output.\n'

## List of ufuncs short for universal functions in numpy

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [18]:
# Universal functions are called ufunc 

a = np.linspace(0, 0.9, 10)
s = np.sin(a)
c = np.cos(a)
print(a)
print(s)
print(c)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691]
[1.         0.99500417 0.98006658 0.95533649 0.92106099 0.87758256
 0.82533561 0.76484219 0.69670671 0.62160997]


In [19]:
# convert angles from radians to degrees

s1 = np.rad2deg(s)
c1 = np.rad2deg(c)
print(s1)
print(c1)

[ 0.          5.72003343 11.38291417 16.9320606  22.31202748 27.46905995
 32.35163066 36.91095457 41.10147642 44.8813259 ]
[57.29577951 57.00953927 56.15367855 54.73674884 52.77290763 50.28177697
 47.28824742 43.82222932 39.918354   35.61562769]


In [20]:
"""
In-class activity - for the above array "a" compute the inverse sine and cosine 
using arcsin and arccos.
"""

'\nIn-class activity - for the above array "a" compute the inverse sine and cosine \nusing arcsin and arccos.\n'

## Array Indexing

In [31]:
# Basic slicing
import numpy as np
a = np.random.rand(5, 5)*5
b = a.astype(np.int)
print(a)
print(b)
print('The rows=1 and cols=2 element is {0}'.format(b[1,2])) 
print('The first col is {0}'.format(b[:,0])) # all rows for cols=0
print('The third row is {0}'.format(b[2, :])) # all cols for rows = 2

[[1.96142039 4.42425731 3.45249822 0.7754491  0.40229976]
 [0.05352902 0.50829171 2.37633903 1.72756001 2.16678995]
 [3.61350339 4.09755163 0.71713601 0.30566    4.55686357]
 [0.04074613 0.74928777 4.96809181 4.44272686 0.25527811]
 [1.73413456 4.58218073 2.36138098 3.26851428 4.28774387]]
[[1 4 3 0 0]
 [0 0 2 1 2]
 [3 4 0 0 4]
 [0 0 4 4 0]
 [1 4 2 3 4]]
The rows=1 and cols=2 element is 2
The first col is [1 0 3 0 1]
The third row is [3 4 0 0 4]


In [22]:
# broadcasting - the process of supplying a value to 
# every element in an array

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array(-1)
c = a + b
print(a)
print(b)
print(c)

[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
-1
[[1 3 7]
 [2 4 6]
 [3 5 9]]


In [23]:
# Another example of broadcasting

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array([1, 1, 1])
c = a + b
print(a)
print(b)
print(c)

[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
[1 1 1]
[[ 3  5  9]
 [ 4  6  8]
 [ 5  7 11]]


In [24]:

a = np.array([[2, 4, 8], [3, 5, 7], [4, 6, 10]])
b = np.array(1)
c = a + b
print(a)
print(b)
print(c)

[[ 2  4  8]
 [ 3  5  7]
 [ 4  6 10]]
1
[[ 3  5  9]
 [ 4  6  8]
 [ 5  7 11]]


In [25]:
# An example of sorting

a = np.array([[2, 5], [6, 4]])
print(a)

print("overall sort is:")
print(np.sort(a)) # sort(a, axis, kind, order)
print("+++++++")
print("sort with order=None")
print(np.sort(a, order = None))
print("+++++++")
print("Sorting along columns")
print(np.sort(a, axis = 0)) # along the column
print("+++++++")
print("Sorting along rows")
print(np.sort(a, axis = 1)) # along the row

[[2 5]
 [6 4]]
overall sort is:
[[2 5]
 [4 6]]
+++++++
sort with order=None
[[2 5]
 [4 6]]
+++++++
Sorting along columns
[[2 4]
 [6 5]]
+++++++
Sorting along rows
[[2 5]
 [4 6]]


In [26]:
 # we can also use sort() method to sort 
    
a.sort() # is same as np.sort(a)
# Note: np.sort(a) this will not alter a
# however, a.sort(), a is modified in place
print(a) 

[[2 5]
 [4 6]]


In [27]:
"""
In-class activity - create an ndarray that is 2 by 3. Then broadcast value -5 to each element. 
Then sort the array first along the columns and then along the rows.
""" 

'\nIn-class activity - create an ndarray that is 2 by 3. Then broadcast value -5 to each element. \nThen sort the array first along the columns and then along the rows.\n'

In [28]:
fcol = np.sort(f, axis=0) # sorting by columns
print("sorting by columns:")
print(fcol)

frow = np.sort(f, axis=1) # sorting by rows
print("sorting by rows:")
print(frow)

NameError: name 'f' is not defined