### In this notebook we will look at

random module

array manipulations

In [1]:
import numpy as np

In [2]:
# random.rand(x) will return an ndarray with x number of items that are 
# randomly selected between 0 and 1
a = np.random.rand(3)
print(a)

[0.0506742  0.96653009 0.25671986]


In [3]:
"""
using sort() to sort the elements in an ndarrray
sort(axis, kind)
all arguments are optional
axis can be specified, default -1 means sort along the last axis

kind can be quicksort, mergesort or heapsort. Default is quicksort
"""

a.sort() 
print(a)

[0.0506742  0.25671986 0.96653009]


In [4]:
a = np.random.rand(2, 4)
print(a, a.dtype)
print(a.nonzero())

[[0.12163233 0.53118856 0.51323408 0.33774266]
 [0.52406948 0.13456116 0.79380214 0.92797606]] float64
(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [5]:
"""
a = [[0.09999404 0.65339454 0.90353863 0.76352847]
      0, 0         0,1        0,2        0,3
     [0.62678425 0.34410054 0.79213342 0.24033324]]
       1,0         1,1        1,2        1,3

0,0  
0,1
0,2

"""

'\na = [[0.09999404 0.65339454 0.90353863 0.76352847]\n      0, 0         0,1        0,2        0,3\n     [0.62678425 0.34410054 0.79213342 0.24033324]]\n       1,0         1,1        1,2        1,3\n\n0,0  \n0,1\n0,2\n\n'

In [6]:
# random.sample will return a random number from a uniform distribution from [0.0, 1.0)
# 1.0 is not included
c = np.random.sample()
print(c)

0.70318883344477


In [7]:
# random.choice(n) will return a number from an ndarray n
a = np.array([2, 6, 12, 18])
print(np.random.choice(a))

2


In [14]:
"""
random.randint(x) will return an integer from the interval  [0, x], both are included
random.randint(x, y) will return an integer from [x, y]
random.randint(x, y, n) will return n integers between x and y
"""

print(np.random.randint(5)) # returned a value between 0 and 5
print(np.random.randint(11, 15)) # returned a value
print(np.random.randint(-10, -5, 2)) # this returned two values 

2
13
[-7 -8]


In [9]:
"""
In-class activity: 
From the list ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"] choose a name
"""

'\nIn-class activity: \nFrom the list ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"] choose a name\n'

In [10]:
list1 = ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"]
import random
c = random.choice(list1)
print(c)

Lisa


In [11]:
# Raanan's solution
lista = ["Elizabeth", "Lisa", "Asha", "Mike", "Amit"]
print("lista is: ",lista)
print("Pick a random name from lista: ", lista[np.random.randint(len(lista))])
print(np.random.choice(lista))

lista is:  ['Elizabeth', 'Lisa', 'Asha', 'Mike', 'Amit']
Pick a random name from lista:  Elizabeth
Amit


In [12]:
"""
In-class activity:
Using random.rand create a 1D ndarray, then convert the values in the ndarray to integer 
and then choose a value from the new int ndarray. At every step print the output. 
"""

'\nIn-class activity:\nUsing random.rand create a 1D ndarray, then convert the values in the ndarray to integer \nand then choose a value from the new int ndarray. At every step print the output. \n'

In [16]:
n3 = np.array([1,3,5,6])
print(n3)

nchoose = np.random.choice(n3)
print(nchoose)

[1 3 5 6]
6


In [17]:
ne = np.random.rand(1,4)
print(ne, ne.ndim)

[[0.10141898 0.99253707 0.39094015 0.32382487]] 2


#### Now we will look at the array manipulation

In [18]:
a = np.array([[2, 4], [7, 9]])
b = np.array([[1, 3], [6, 5]])
print("a:")
print(a)
print("b:")
print(b)

a:
[[2 4]
 [7 9]]
b:
[[1 3]
 [6 5]]


In [19]:
# using + operator we can compute element by element sum of two arrays
print(a + b)

[[ 3  7]
 [13 14]]


In [20]:
# using * operator we can compute element by element multiplication of two arrays

print(a * b) # element by element multiplication

[[ 2 12]
 [42 45]]


In [21]:
# using - operator we can compute element by element subtraction of two arrays

print(a - b)

[[1 1]
 [1 4]]


In [22]:
# dot(a1, a2) will compute matrix multiplication

print(np.dot(a, b)) # matrix multiplication 

[[26 26]
 [61 66]]


In [23]:
# np.dot(m1, m2)
# the number of cloumns in m1 should match number of rows in m2

In [24]:
# @ can be used to perform matrix multiplication 
# @  is called the 'infix' operator and is only available in Python 3.5+ (PEP 465)

print(a @ b)

[[26 26]
 [61 66]]


In [25]:
# if we have matrices then we can perfrom matrix multiplication using matmul(a1, a2)

print(np.matmul(a, b)) # matrix multiplication

[[26 26]
 [61 66]]


In [26]:
"""
[[4, 7, 9]
 [5, 7, 10]]
 
 2 by 3
"""

'\n[[4, 7, 9]\n [5, 7, 10]]\n \n 2 by 3\n'

In [27]:
# in an array transpose() will interchange the rows to columns 
# and vice-versa 

print(np.transpose([[4, 7, 9], [5, 7, 10]]))

[[ 4  5]
 [ 7  7]
 [ 9 10]]


In [28]:
# T can also be used to transpose a matrix

y = np.array([[3, 5, 1], [8, 11, 0]])
print("Original array")
print(y)
print("Transposed array")
print(y.T)

Original array
[[ 3  5  1]
 [ 8 11  0]]
Transposed array
[[ 3  8]
 [ 5 11]
 [ 1  0]]


In [ ]:
"""
In-class activity:
Create two 2-by-2 ndarrays. Compute the following:

1) Element by element multiplication

2) Array multiplication using two different methods of your choice

element by element
a m-by-n
b m-by-n (or) 1-by-1 (or) n-by-1

@ matmul
a m-by-n
b n-by-k
"""

In [30]:
"""
In-class activity:
Create a 2-by-2 ndarray. Compute the following:

1) Transpose of the ndarray

2) array multiplication of the old array and the transposed array
"""

'\nIn-class activity:\nCreate a 2-by-2 ndarray. Compute the following:\n\n1) Transpose of the ndarray\n\n2) array multiplication of the old array and the transposed array\n'

In [31]:
a = np.array([[1,2,3],[4,5,6]])
b = np.transpose(a)
print(a.shape, b.shape)
c = a@b
print(c)
print(c.shape)

(2, 3) (3, 2)
[[14 32]
 [32 77]]
(2, 2)
