### In this notebook we will discuss Boolean Operations

Boolean returns with True or False

In [1]:
import numpy as np

In [23]:
c = np.array([[4, 2, 6],[7, 10, 11]], dtype=np.float32)
d = np.linspace(start=10, stop=13, num=3)
print(c)
print(d)

[[ 4.  2.  6.]
 [ 7. 10. 11.]]
[10.  11.5 13. ]


In [3]:
f = 10*c # is similar to braodcasting, we are multiplying every element in c by 10.

# Multiply a matrix with scalar. 
# The matrix e is of dtype=int64 but the final matrix is of dtype=float64

print(f, f.dtype)

[[ 40.  20.  60.]
 [ 70. 100. 110.]] float32


In [4]:
f = d-c # Subtract matrix
print(f, f.dtype)

[[6.  9.5 7. ]
 [3.  1.5 2. ]] float64


In [5]:
h = f > 5 # Compare every element with the value of 5
print(h)

[[ True  True  True]
 [False False False]]


In [6]:
# Indexing with boolean arrays
k = f > 5
print(k)
print(f[k]) # Returns values in f that are True in k

[[ True  True  True]
 [False False False]]
[6.  9.5 7. ]


In [7]:
print(f[f>5]) # This is same as the previous line except that we are not creating a new array k

[6.  9.5 7. ]


In [8]:
t = np.array([[-2, 4, -3],[-1, 7, 0]])

In [9]:
t1 = t > -3
print(t1)

[[ True  True False]
 [ True  True  True]]


In [10]:
print(t[t1])

[-2  4 -1  7  0]


In [11]:
print(t[t > -3])

[-2  4 -1  7  0]


In [12]:
# where(condition) will returns indices where the condition is true 

a = np.array([[7, 8, 4],[5, 6, 9]]) 
print(a)
print("indices where the value is greater than 5 ")
b = np.where(a>5)
print(b)

[[7 8 4]
 [5 6 9]]
indices where the value is greater than 5 
(array([0, 0, 1, 1], dtype=int64), array([0, 1, 1, 2], dtype=int64))


In [13]:
# any(z) returns a boolean value when a certain condition is met in z at least once

print(np.any(a > 6)) 

True


In [14]:
# all (z) returns a boolean value when a certain condition is met by all the elements in z

print(np.all(a>7)) # since not all values are greater than 7

False


In [15]:
# logical_and will boolean values and returns a boolean value

print(np.logical_and(True, False))

False


In [16]:
print(np.logical_and(True, True))

True


In [17]:
print(np.logical_and(False, False))

False


In [18]:
print(np.logical_and([False, False], [False, True]))

[False False]


In [19]:
# logical_and will take 

s1 = np.array([3, 6, 9, 12])
print(np.logical_and(s1>5, s1%2==0))

[False  True False  True]


In [20]:
"""
In-class activity:

Create a 2 by 3 ndarray with integer values. Compute the following:
1) Mean of the array
2) Boolean array where the value is greater than the mean
3) Only print the values in the original array that statisfies condition in 2.)
"""

'\nIn-class activity:\n\nCreate a 2 by 3 ndarray with integer values. Compute the following:\n1) Mean of the array\n2) Boolean array where the value is greater than the mean\n3) Only print the values in the original array that statisfies condition in 2.)\n'

In [21]:
#arr = 5*np.random.rand(2,3)
#arr = arr.astype(np.int)
arr = np.random.randint(0, 5, (2, 3))
print(arr)
mean_value = np.mean(arr)
print(mean_value)
bool_arr = arr > mean_value
print(bool_arr)
print(arr[bool_arr])

[[4 2 2]
 [2 0 2]]
2.0
[[ True False False]
 [False False False]]
[4]


In [22]:
"""
In-class activity:

Create a 1D ndarray with integers. Find the following:

1) Median of the ndarray

2) Use "any" to find greater than the median

3) Use "all" to find greater than the median

4) Use "where" to find less than median

"""

'\nIn-class activity:\n\nCreate a 1D ndarray with integers. Find the following:\n\n1) Median of the ndarray\n\n2) Use "any" to find greater than the median\n\n3) Use "all" to find greater than the median\n\n4) Use "where" to find less than median\n\n'

In [34]:
arr2 = np.random.randint(0, 10, 5)
print(arr2)
median = np.median(arr2)
print("median", median)
arr2_any = np.any(arr2 > median)
print(arr2_any)
arr2_all = np.all(arr2 > median)
print(arr2_all)
arr2_where = np.where(arr2 < median)
print(arr2_where)

[7 9 7 6 1]
median 7.0
True
False
(array([3, 4], dtype=int64),)
